plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'io.dcloud.uts.kotlin'
}

android {
    namespace 'cn.uvuejs.uniappx'
    compileSdk 35

    defaultConfig {
        minSdk 21

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    aaptOptions {
        additionalParameters '--auto-add-overlay'
        ignoreAssetsPattern '!.svn:!.git:.*:!CVS:!thumbs.db:!picasa.ini:!*.scc:*~'
    }
}

dependencies {
    compileOnly fileTree(include: ['*.aar', '*.jar'], dir: './libs')
	compileOnly fileTree(include: ['*.aar', '*.jar'], dir: '../app/libs')
    // implementation("androidx.core:core-ktx:1.8.0")
	implementation("androidx.core:core-ktx:1.10.1")
    // implementation("androidx.recyclerview:recyclerview:1.0.0")
	implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("androidx.appcompat:appcompat:1.0.0")
    implementation("androidx.exifinterface:exifinterface:1.3.6")
    implementation("androidx.localbroadcastmanager:localbroadcastmanager:1.0.0@aar")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("com.google.android.material:material:1.4.0")
    implementation("androidx.viewpager2:viewpager2:1.1.0-beta02")
    implementation("com.alibaba:fastjson:1.2.83")
    implementation("com.facebook.fresco:fresco:3.4.0")
    implementation("com.facebook.fresco:middleware:3.4.0")
    implementation("com.facebook.fresco:animated-gif:3.4.0")
    implementation("com.facebook.fresco:webpsupport:3.4.0")
    implementation("com.facebook.fresco:animated-webp:3.4.0")
    implementation("com.caverock:androidsvg:1.4")
    implementation("com.github.bumptech.glide:glide:4.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.2.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")
    implementation("com.squareup.okhttp3:okhttp:3.12.12")
    // implementation("com.github.getActivity:XXPermissions:18.0")
	implementation("com.github.getActivity:XXPermissions:18.63")
	
	implementation("net.lingala.zip4j:zip4j:2.11.5")
	implementation("androidx.webkit:webkit:1.6.0")
    implementation project(':iboxs-amap')
    implementation project(':iboxs-Biometric')
    implementation project(':iboxs-BleBluetooth')
    implementation project(':iboxs-Bluetooth')
    implementation project(':iboxs-choosemedia')
    implementation project(':iboxs-clipboard')
    implementation project(':iboxs-common')
    implementation project(':iboxs-docscan')
    implementation project(':iboxs-Nfc')
    implementation project(':iboxs-notice')
    implementation project(':iboxs-ocr')
    implementation project(':iboxs-performance')
    implementation project(':iboxs-qcloudCos')
    implementation project(':iboxs-Quicklogin')
    implementation project(':iboxs-scancode')
    implementation project(':iboxs-sqlite')
    implementation project(':iboxs-tpop')
    implementation project(':iboxs-tts')
    implementation project(':iboxs-Zimfacade')
    implementation project(':kux-broadcast-receiver')
    implementation project(':lime-pdf')
    implementation project(':lime-svg')
    implementation project(':tmx-call-phone')
    implementation project(':tmx-crypto-s')
    implementation project(':tmx-loading-s')
    implementation project(':tmx-modal-s')
    implementation project(':tmx-network-change')
    implementation project(':tmx-texttovoice-s')
    implementation project(':tmx-tips-s')
    implementation project(':tmx-toast-s')
    implementation project(':uni-MemoryInfo')
    implementation project(':uni-unimp')
    implementation project(':uni-usercapturescreen')
    implementation project(':x-md5')
    implementation project(':x-uuid')
}
